version: '3'
services: 
    node:
        image: andropoulos/task6_node:node
        build: .
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - postgres
        restart: on-failure
        volumes: 
            - data:/src
        environment: 
            PORT: ${PORT}
        networks: 
            - app-net
    postgres:
        image: andropoulos/task6_postgres:postgres
        build: ./database/
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes: 
            - data:/var/lib/postgresql/data
        networks:
            - app-net
        restart: on-failure
networks:
    app-net:
        driver: bridge
volumes: 
    data: